name: Love2d iOS build test
run-name: ${{ github.actor }} is trying to build a Love2d app 
on: [push]

jobs:   
    ios-build:
      runs-on: macos-latest
      steps:
       - name: Love actions for iOS
         uses: love-actions/love-actions-ios@v1.1.3
         with:
          app-name: "Love Example Browser"
          bundle-id: "com.redmarbles.loveexample"
          icon-path: ./.github/build/iOS/${{ env.BUILD_TYPE }}/icon
          love-patch: ./.github/build/iOS/love.patch
          love-ref: "383fec4ea5233e282acadcfc9e28246b51f0c17e"
          product-name: "Love Example Browser"
          version-string: "1.0.0"
          output-folder: ${{ env.OUTPUT_FOLDER }}
          apple-development-base64: ${{ secrets.APPLE_CERT_APPLE_DEVELOPMENT_BASE64 }}
          apple-development-password: ${{ secrets.APPLE_CERT_APPLE_DEVELOPMENT_PWD }}
          api-key: ${{ secrets.APPLE_API_KEY }}
          api-key-id: ${{ secrets.APPLE_API_KEY_ID }}
          api-issuer-id: ${{ secrets.APPLE_API_ISSUER_ID }}
          team-id: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
          apple-id: ${{ secrets.APPLE_APPLE_ID }}
          external-test: ${{ startsWith(github.ref, 'refs/tags/pre') }}
          store-release: ${{ startsWith(github.ref, 'refs/tags/v') }}
       
